apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc


  template:
    metadata:
      name: '{{cluster}}-prometheus'


    spec:
      source:
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 8.15.0
        chart: kube-prometheus

        helm:
          releaseName: 'stable'
          version: v3      


      destination:
        server: '{{url}}'
        namespace: prometheus

      # The project the application belongs to.
      project: default

      # Sync policy
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - Validate=true
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        # - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
